server.port=8080

spring.datasource.url=jdbc:postgresql://185.240.103.76:5432/calendarpb
spring.datasource.username=postgres
spring.datasource.password=diko1793

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

